marketplaceMTC/marketplaceMTC-war/src/java/com/marketplaceMTC/vista/managedbeans/PaquetesController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marketplaceMTC.vista.managedbeans;

import com.marketplaceMTC.entities.Paquetes;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.transaction.UserTransaction;
import com.marketplaceMTC.vista.managedbeans.util.JsfUtil;
import com.marketplaceMTC.vista.managedbeans.util.PagingInfo;
import com.marketplaceMTC.session.PaquetesFacade;
import java.util.List;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;

/**
 *
 * @author Miguel
 */
public class PaquetesController {

  public PaquetesController() {
    pagingInfo = new PagingInfo();
    converter = new PaquetesConverter();
  }
  private Paquetes paquetes = null;
  private List<Paquetes> paquetesItems = null;
  private PaquetesFacade jpaController = null;
  private PaquetesConverter converter = null;
  private PagingInfo pagingInfo = null;
  @Resource
  private UserTransaction utx = null;
  @PersistenceUnit(unitName = "marketplaceMTC-warPU")
  private EntityManagerFactory emf = null;

  public PagingInfo getPagingInfo() {
    if (pagingInfo.getItemCount() == -1) {
      pagingInfo.setItemCount(getJpaController().count());
    }
    return pagingInfo;
  }

  public PaquetesFacade getJpaController() {
    if (jpaController == null) {
      FacesContext facesContext = FacesContext.getCurrentInstance();
      jpaController = (PaquetesFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "paquetesJpa");
    }
    return jpaController;
  }

  public SelectItem[] getPaquetesItemsAvailableSelectMany() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), false);
  }

  public SelectItem[] getPaquetesItemsAvailableSelectOne() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), true);
  }

  public Paquetes getPaquetes() {
    if (paquetes == null) {
      paquetes = (Paquetes) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentPaquetes", converter, null);
    }
    if (paquetes == null) {
      paquetes = new Paquetes();
    }
    return paquetes;
  }

  public String listSetup() {
    reset(true);
    return "paquetes_list";
  }

  public String createSetup() {
    reset(false);
    paquetes = new Paquetes();
    return "paquetes_create";
  }

  public String create() {
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().create(paquetes);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Paquetes was successfully created.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return listSetup();
  }

  public String detailSetup() {
    return scalarSetup("paquetes_detail");
  }

  public String editSetup() {
    return scalarSetup("paquetes_edit");
  }

  private String scalarSetup(String destination) {
    reset(false);
    paquetes = (Paquetes) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentPaquetes", converter, null);
    if (paquetes == null) {
      String requestPaquetesString = JsfUtil.getRequestParameter("jsfcrud.currentPaquetes");
      JsfUtil.addErrorMessage("The paquetes with id " + requestPaquetesString + " no longer exists.");
      return relatedOrListOutcome();
    }
    return destination;
  }

  public String edit() {
    String paquetesString = converter.getAsString(FacesContext.getCurrentInstance(), null, paquetes);
    String currentPaquetesString = JsfUtil.getRequestParameter("jsfcrud.currentPaquetes");
    if (paquetesString == null || paquetesString.length() == 0 || !paquetesString.equals(currentPaquetesString)) {
      String outcome = editSetup();
      if ("paquetes_edit".equals(outcome)) {
        JsfUtil.addErrorMessage("Could not edit paquetes. Try again.");
      }
      return outcome;
    }
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().edit(paquetes);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Paquetes was successfully updated.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return detailSetup();
  }

  public String remove() {
    String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentPaquetes");
    Integer id = new Integer(idAsString);
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().remove(getJpaController().find(id));
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Paquetes was successfully deleted.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return relatedOrListOutcome();
  }

  private String relatedOrListOutcome() {
    String relatedControllerOutcome = relatedControllerOutcome();
    if (relatedControllerOutcome != null) {
      return relatedControllerOutcome;
    }
    return listSetup();
  }

  public List<Paquetes> getPaquetesItems() {
    if (paquetesItems == null) {
      getPagingInfo();
      paquetesItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
    }
    return paquetesItems;
  }

  public String next() {
    reset(false);
    getPagingInfo().nextPage();
    return "paquetes_list";
  }

  public String prev() {
    reset(false);
    getPagingInfo().previousPage();
    return "paquetes_list";
  }

  private String relatedControllerOutcome() {
    String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
    String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
    if (relatedControllerString != null && relatedControllerTypeString != null) {
      FacesContext context = FacesContext.getCurrentInstance();
      Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
      try {
        Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
        Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
        return (String) detailSetupMethod.invoke(relatedController);
      } catch (ClassNotFoundException e) {
        throw new FacesException(e);
      } catch (NoSuchMethodException e) {
        throw new FacesException(e);
      } catch (IllegalAccessException e) {
        throw new FacesException(e);
      } catch (InvocationTargetException e) {
        throw new FacesException(e);
      }
    }
    return null;
  }

  private void reset(boolean resetFirstItem) {
    paquetes = null;
    paquetesItems = null;
    pagingInfo.setItemCount(-1);
    if (resetFirstItem) {
      pagingInfo.setFirstItem(0);
    }
  }

  public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
    Paquetes newPaquetes = new Paquetes();
    String newPaquetesString = converter.getAsString(FacesContext.getCurrentInstance(), null, newPaquetes);
    String paquetesString = converter.getAsString(FacesContext.getCurrentInstance(), null, paquetes);
    if (!newPaquetesString.equals(paquetesString)) {
      createSetup();
    }
  }

  public Converter getConverter() {
    return converter;
  }
  
}

marketplaceMTC/marketplaceMTC-war/web/usuarios/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Editing Usuarios</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Editing Usuarios</h1>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputText value="Id:"/>
        <h:outputText value="#{usuarios.usuarios.id}" title="Id" />
        <h:outputText value="PrimerNombre:"/>
        <h:inputText id="primerNombre" value="#{usuarios.usuarios.primerNombre}" title="PrimerNombre" />
        <h:outputText value="SegundoNombre:"/>
        <h:inputText id="segundoNombre" value="#{usuarios.usuarios.segundoNombre}" title="SegundoNombre" />
        <h:outputText value="PrimerApellido:"/>
        <h:inputText id="primerApellido" value="#{usuarios.usuarios.primerApellido}" title="PrimerApellido" />
        <h:outputText value="SegundoApellido:"/>
        <h:inputText id="segundoApellido" value="#{usuarios.usuarios.segundoApellido}" title="SegundoApellido" />
        <h:outputText value="NombreComercial:"/>
        <h:inputText id="nombreComercial" value="#{usuarios.usuarios.nombreComercial}" title="NombreComercial" />
        <h:outputText value="Nickname:"/>
        <h:inputText id="nickname" value="#{usuarios.usuarios.nickname}" title="Nickname" required="true" requiredMessage="The nickname field is required." />
        <h:outputText value="Contrasena:"/>
        <h:inputText id="contrasena" value="#{usuarios.usuarios.contrasena}" title="Contrasena" required="true" requiredMessage="The contrasena field is required." />
        <h:outputText value="Correo:"/>
        <h:inputText id="correo" value="#{usuarios.usuarios.correo}" title="Correo" />
        <h:outputText value="IdPerfil:"/>
        <h:inputText id="idPerfil" value="#{usuarios.usuarios.idPerfil}" title="IdPerfil" />
        <h:outputText value="Estado:"/>
        <h:inputText id="estado" value="#{usuarios.usuarios.estado}" title="Estado" required="true" requiredMessage="The estado field is required." />
        <h:outputText value="PaquetesList:"/>
        <h:selectManyListbox id="paquetesList" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].paquetesList}" title="PaquetesList" size="6" converter="#{paquetes.converter}" >
          <f:selectItems value="#{paquetes.paquetesItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="PreguntasList:"/>
        <h:selectManyListbox id="preguntasList" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].preguntasList}" title="PreguntasList" size="6" converter="#{preguntas.converter}" >
          <f:selectItems value="#{preguntas.preguntasItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="PreguntasList1:"/>
        <h:selectManyListbox id="preguntasList1" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].preguntasList1}" title="PreguntasList1" size="6" converter="#{preguntas.converter}" >
          <f:selectItems value="#{preguntas.preguntasItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="TransaccionesList:"/>
        <h:selectManyListbox id="transaccionesList" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].transaccionesList}" title="TransaccionesList" size="6" converter="#{transacciones.converter}" >
          <f:selectItems value="#{transacciones.transaccionesItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{usuarios.edit}" value="Save">
        <f:param name="jsfcrud.currentUsuarios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuarios.usuarios][usuarios.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <br />
      <h:commandLink action="#{usuarios.detailSetup}" value="Show" immediate="true">
        <f:param name="jsfcrud.currentUsuarios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuarios.usuarios][usuarios.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <h:commandLink action="#{usuarios.listSetup}" value="Show All Usuarios Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/usuarios/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Listing Usuarios Items</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Listing Usuarios Items</h1>
    <h:form styleClass="jsfcrud_list_form">
      <h:outputText escape="false" value="(No Usuarios Items Found)<br />" rendered="#{usuarios.pagingInfo.itemCount == 0}" />
      <h:panelGroup rendered="#{usuarios.pagingInfo.itemCount > 0}">
        <h:outputText value="Item #{usuarios.pagingInfo.firstItem + 1}..#{usuarios.pagingInfo.lastItem} of #{usuarios.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{usuarios.prev}" value="Previous #{usuarios.pagingInfo.batchSize}" rendered="#{usuarios.pagingInfo.firstItem >= usuarios.pagingInfo.batchSize}"/>&nbsp;
        <h:commandLink action="#{usuarios.next}" value="Next #{usuarios.pagingInfo.batchSize}" rendered="#{usuarios.pagingInfo.lastItem + usuarios.pagingInfo.batchSize <= usuarios.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{usuarios.next}" value="Remaining #{usuarios.pagingInfo.itemCount - usuarios.pagingInfo.lastItem}"
                       rendered="#{usuarios.pagingInfo.lastItem < usuarios.pagingInfo.itemCount && usuarios.pagingInfo.lastItem + usuarios.pagingInfo.batchSize > usuarios.pagingInfo.itemCount}"/>
        <h:dataTable value="#{usuarios.usuariosItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
          <h:column>
            <f:facet name="header">
              <h:outputText value="Id"/>
            </f:facet>
            <h:outputText value="#{item.id}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="PrimerNombre"/>
            </f:facet>
            <h:outputText value="#{item.primerNombre}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="SegundoNombre"/>
            </f:facet>
            <h:outputText value="#{item.segundoNombre}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="PrimerApellido"/>
            </f:facet>
            <h:outputText value="#{item.primerApellido}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="SegundoApellido"/>
            </f:facet>
            <h:outputText value="#{item.segundoApellido}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="NombreComercial"/>
            </f:facet>
            <h:outputText value="#{item.nombreComercial}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Nickname"/>
            </f:facet>
            <h:outputText value="#{item.nickname}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Contrasena"/>
            </f:facet>
            <h:outputText value="#{item.contrasena}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Correo"/>
            </f:facet>
            <h:outputText value="#{item.correo}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="IdPerfil"/>
            </f:facet>
            <h:outputText value="#{item.idPerfil}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Estado"/>
            </f:facet>
            <h:outputText value="#{item.estado}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText escape="false" value="&nbsp;"/>
            </f:facet>
            <h:commandLink value="Show" action="#{usuarios.detailSetup}">
              <f:param name="jsfcrud.currentUsuarios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuarios.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Edit" action="#{usuarios.editSetup}">
              <f:param name="jsfcrud.currentUsuarios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuarios.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Destroy" action="#{usuarios.remove}">
              <f:param name="jsfcrud.currentUsuarios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuarios.converter].jsfcrud_invoke}"/>
            </h:commandLink>
          </h:column>

        </h:dataTable>
      </h:panelGroup>
      <br />
      <h:commandLink action="#{usuarios.createSetup}" value="New Usuarios"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />


    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/usuarios/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>New Usuarios</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>New Usuarios</h1>
    <h:form>
      <h:inputHidden id="validateCreateField" validator="#{usuarios.validateCreate}" value="value"/>
      <h:panelGrid columns="2">
        <h:outputText value="Id:"/>
        <h:inputText id="id" value="#{usuarios.usuarios.id}" title="Id" required="true" requiredMessage="The id field is required." />
        <h:outputText value="PrimerNombre:"/>
        <h:inputText id="primerNombre" value="#{usuarios.usuarios.primerNombre}" title="PrimerNombre" />
        <h:outputText value="SegundoNombre:"/>
        <h:inputText id="segundoNombre" value="#{usuarios.usuarios.segundoNombre}" title="SegundoNombre" />
        <h:outputText value="PrimerApellido:"/>
        <h:inputText id="primerApellido" value="#{usuarios.usuarios.primerApellido}" title="PrimerApellido" />
        <h:outputText value="SegundoApellido:"/>
        <h:inputText id="segundoApellido" value="#{usuarios.usuarios.segundoApellido}" title="SegundoApellido" />
        <h:outputText value="NombreComercial:"/>
        <h:inputText id="nombreComercial" value="#{usuarios.usuarios.nombreComercial}" title="NombreComercial" />
        <h:outputText value="Nickname:"/>
        <h:inputText id="nickname" value="#{usuarios.usuarios.nickname}" title="Nickname" required="true" requiredMessage="The nickname field is required." />
        <h:outputText value="Contrasena:"/>
        <h:inputText id="contrasena" value="#{usuarios.usuarios.contrasena}" title="Contrasena" required="true" requiredMessage="The contrasena field is required." />
        <h:outputText value="Correo:"/>
        <h:inputText id="correo" value="#{usuarios.usuarios.correo}" title="Correo" />
        <h:outputText value="IdPerfil:"/>
        <h:inputText id="idPerfil" value="#{usuarios.usuarios.idPerfil}" title="IdPerfil" />
        <h:outputText value="Estado:"/>
        <h:inputText id="estado" value="#{usuarios.usuarios.estado}" title="Estado" required="true" requiredMessage="The estado field is required." />
        <h:outputText value="PaquetesList:"/>
        <h:selectManyListbox id="paquetesList" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].paquetesList}" title="PaquetesList" size="6" converter="#{paquetes.converter}" >
          <f:selectItems value="#{paquetes.paquetesItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="PreguntasList:"/>
        <h:selectManyListbox id="preguntasList" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].preguntasList}" title="PreguntasList" size="6" converter="#{preguntas.converter}" >
          <f:selectItems value="#{preguntas.preguntasItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="PreguntasList1:"/>
        <h:selectManyListbox id="preguntasList1" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].preguntasList1}" title="PreguntasList1" size="6" converter="#{preguntas.converter}" >
          <f:selectItems value="#{preguntas.preguntasItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="TransaccionesList:"/>
        <h:selectManyListbox id="transaccionesList" value="#{usuarios.usuarios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].transaccionesList}" title="TransaccionesList" size="6" converter="#{transacciones.converter}" >
          <f:selectItems value="#{transacciones.transaccionesItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{usuarios.create}" value="Create"/>
      <br />
      <br />
      <h:commandLink action="#{usuarios.listSetup}" value="Show All Usuarios Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>