marketplaceMTC/marketplaceMTC-war/src/java/com/marketplaceMTC/vista/managedbeans/ArchivosadjuntosController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marketplaceMTC.vista.managedbeans;

import com.marketplaceMTC.entities.Archivosadjuntos;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.transaction.UserTransaction;
import com.marketplaceMTC.vista.managedbeans.util.JsfUtil;
import com.marketplaceMTC.vista.managedbeans.util.PagingInfo;
import com.marketplaceMTC.session.ArchivosadjuntosFacade;
import java.util.List;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;

/**
 *
 * @author Miguel
 */
public class ArchivosadjuntosController {

  public ArchivosadjuntosController() {
    pagingInfo = new PagingInfo();
    converter = new ArchivosadjuntosConverter();
  }
  private Archivosadjuntos archivosadjuntos = null;
  private List<Archivosadjuntos> archivosadjuntosItems = null;
  private ArchivosadjuntosFacade jpaController = null;
  private ArchivosadjuntosConverter converter = null;
  private PagingInfo pagingInfo = null;
  @Resource
  private UserTransaction utx = null;
  @PersistenceUnit(unitName = "marketplaceMTC-warPU")
  private EntityManagerFactory emf = null;

  public PagingInfo getPagingInfo() {
    if (pagingInfo.getItemCount() == -1) {
      pagingInfo.setItemCount(getJpaController().count());
    }
    return pagingInfo;
  }

  public ArchivosadjuntosFacade getJpaController() {
    if (jpaController == null) {
      FacesContext facesContext = FacesContext.getCurrentInstance();
      jpaController = (ArchivosadjuntosFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "archivosadjuntosJpa");
    }
    return jpaController;
  }

  public SelectItem[] getArchivosadjuntosItemsAvailableSelectMany() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), false);
  }

  public SelectItem[] getArchivosadjuntosItemsAvailableSelectOne() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), true);
  }

  public Archivosadjuntos getArchivosadjuntos() {
    if (archivosadjuntos == null) {
      archivosadjuntos = (Archivosadjuntos) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentArchivosadjuntos", converter, null);
    }
    if (archivosadjuntos == null) {
      archivosadjuntos = new Archivosadjuntos();
    }
    return archivosadjuntos;
  }

  public String listSetup() {
    reset(true);
    return "archivosadjuntos_list";
  }

  public String createSetup() {
    reset(false);
    archivosadjuntos = new Archivosadjuntos();
    return "archivosadjuntos_create";
  }

  public String create() {
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().create(archivosadjuntos);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Archivosadjuntos was successfully created.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return listSetup();
  }

  public String detailSetup() {
    return scalarSetup("archivosadjuntos_detail");
  }

  public String editSetup() {
    return scalarSetup("archivosadjuntos_edit");
  }

  private String scalarSetup(String destination) {
    reset(false);
    archivosadjuntos = (Archivosadjuntos) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentArchivosadjuntos", converter, null);
    if (archivosadjuntos == null) {
      String requestArchivosadjuntosString = JsfUtil.getRequestParameter("jsfcrud.currentArchivosadjuntos");
      JsfUtil.addErrorMessage("The archivosadjuntos with id " + requestArchivosadjuntosString + " no longer exists.");
      return relatedOrListOutcome();
    }
    return destination;
  }

  public String edit() {
    String archivosadjuntosString = converter.getAsString(FacesContext.getCurrentInstance(), null, archivosadjuntos);
    String currentArchivosadjuntosString = JsfUtil.getRequestParameter("jsfcrud.currentArchivosadjuntos");
    if (archivosadjuntosString == null || archivosadjuntosString.length() == 0 || !archivosadjuntosString.equals(currentArchivosadjuntosString)) {
      String outcome = editSetup();
      if ("archivosadjuntos_edit".equals(outcome)) {
        JsfUtil.addErrorMessage("Could not edit archivosadjuntos. Try again.");
      }
      return outcome;
    }
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().edit(archivosadjuntos);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Archivosadjuntos was successfully updated.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return detailSetup();
  }

  public String remove() {
    String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentArchivosadjuntos");
    Integer id = new Integer(idAsString);
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().remove(getJpaController().find(id));
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Archivosadjuntos was successfully deleted.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return relatedOrListOutcome();
  }

  private String relatedOrListOutcome() {
    String relatedControllerOutcome = relatedControllerOutcome();
    if (relatedControllerOutcome != null) {
      return relatedControllerOutcome;
    }
    return listSetup();
  }

  public List<Archivosadjuntos> getArchivosadjuntosItems() {
    if (archivosadjuntosItems == null) {
      getPagingInfo();
      archivosadjuntosItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
    }
    return archivosadjuntosItems;
  }

  public String next() {
    reset(false);
    getPagingInfo().nextPage();
    return "archivosadjuntos_list";
  }

  public String prev() {
    reset(false);
    getPagingInfo().previousPage();
    return "archivosadjuntos_list";
  }

  private String relatedControllerOutcome() {
    String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
    String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
    if (relatedControllerString != null && relatedControllerTypeString != null) {
      FacesContext context = FacesContext.getCurrentInstance();
      Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
      try {
        Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
        Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
        return (String) detailSetupMethod.invoke(relatedController);
      } catch (ClassNotFoundException e) {
        throw new FacesException(e);
      } catch (NoSuchMethodException e) {
        throw new FacesException(e);
      } catch (IllegalAccessException e) {
        throw new FacesException(e);
      } catch (InvocationTargetException e) {
        throw new FacesException(e);
      }
    }
    return null;
  }

  private void reset(boolean resetFirstItem) {
    archivosadjuntos = null;
    archivosadjuntosItems = null;
    pagingInfo.setItemCount(-1);
    if (resetFirstItem) {
      pagingInfo.setFirstItem(0);
    }
  }

  public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
    Archivosadjuntos newArchivosadjuntos = new Archivosadjuntos();
    String newArchivosadjuntosString = converter.getAsString(FacesContext.getCurrentInstance(), null, newArchivosadjuntos);
    String archivosadjuntosString = converter.getAsString(FacesContext.getCurrentInstance(), null, archivosadjuntos);
    if (!newArchivosadjuntosString.equals(archivosadjuntosString)) {
      createSetup();
    }
  }

  public Converter getConverter() {
    return converter;
  }
  
}

marketplaceMTC/marketplaceMTC-war/web/archivos/Detail.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Archivos Detail</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Archivos Detail</h1>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputText value="Id:"/>
        <h:outputText value="#{archivos.archivos.id}" title="Id" />
        <h:outputText value="Tipo:"/>
        <h:outputText value="#{archivos.archivos.tipo}" title="Tipo" />
        <h:outputText value="Ruta:"/>
        <h:outputText value="#{archivos.archivos.ruta}" title="Ruta" />

        <h:outputText value="ArchivosadjuntosList:" />
        <h:panelGroup>
          <h:outputText rendered="#{empty archivos.archivos.archivosadjuntosList}" value="(No Items)"/>
          <h:dataTable value="#{archivos.archivos.archivosadjuntosList}" var="item" 
                       border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px" 
                       rendered="#{not empty archivos.archivos.archivosadjuntosList}">
            <h:column>
              <f:facet name="header">
                <h:outputText value="Id"/>
              </f:facet>
              <h:outputText value="#{item.id}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="IdArchivo"/>
              </f:facet>
              <h:outputText value="#{item.idArchivo}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="IdAdjunto"/>
              </f:facet>
              <h:outputText value="#{item.idAdjunto}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText escape="false" value="&nbsp;"/>
              </f:facet>
              <h:commandLink value="Show" action="#{archivosadjuntos.detailSetup}">
                <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][archivos.archivos][archivos.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.currentArchivosadjuntos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][archivosadjuntos.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.relatedController" value="archivos" />
                <f:param name="jsfcrud.relatedControllerType" value="com.marketplaceMTC.vista.managedbeans.ArchivosController" />
              </h:commandLink>
              <h:outputText value=" "/>
              <h:commandLink value="Edit" action="#{archivosadjuntos.editSetup}">
                <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][archivos.archivos][archivos.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.currentArchivosadjuntos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][archivosadjuntos.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.relatedController" value="archivos" />
                <f:param name="jsfcrud.relatedControllerType" value="com.marketplaceMTC.vista.managedbeans.ArchivosController" />
              </h:commandLink>
              <h:outputText value=" "/>
              <h:commandLink value="Destroy" action="#{archivosadjuntos.destroy}">
                <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][archivos.archivos][archivos.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.currentArchivosadjuntos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][archivosadjuntos.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.relatedController" value="archivos" />
                <f:param name="jsfcrud.relatedControllerType" value="com.marketplaceMTC.vista.managedbeans.ArchivosController" />
              </h:commandLink>
            </h:column>
          </h:dataTable>
        </h:panelGroup>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{archivos.remove}" value="Destroy">
        <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][archivos.archivos][archivos.converter].jsfcrud_invoke}" />
      </h:commandLink>
      <br />
      <br />
      <h:commandLink action="#{archivos.editSetup}" value="Edit">
        <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][archivos.archivos][archivos.converter].jsfcrud_invoke}" />
      </h:commandLink>
      <br />
      <h:commandLink action="#{archivos.createSetup}" value="New Archivos" />
      <br />
      <h:commandLink action="#{archivos.listSetup}" value="Show All Archivos Items"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/archivos/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Editing Archivos</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Editing Archivos</h1>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputText value="Id:"/>
        <h:outputText value="#{archivos.archivos.id}" title="Id" />
        <h:outputText value="Tipo:"/>
        <h:inputText id="tipo" value="#{archivos.archivos.tipo}" title="Tipo" required="true" requiredMessage="The tipo field is required." />
        <h:outputText value="Ruta:"/>
        <h:inputText id="ruta" value="#{archivos.archivos.ruta}" title="Ruta" required="true" requiredMessage="The ruta field is required." />
        <h:outputText value="ArchivosadjuntosList:"/>
        <h:selectManyListbox id="archivosadjuntosList" value="#{archivos.archivos.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].archivosadjuntosList}" title="ArchivosadjuntosList" size="6" converter="#{archivosadjuntos.converter}" >
          <f:selectItems value="#{archivosadjuntos.archivosadjuntosItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{archivos.edit}" value="Save">
        <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][archivos.archivos][archivos.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <br />
      <h:commandLink action="#{archivos.detailSetup}" value="Show" immediate="true">
        <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][archivos.archivos][archivos.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <h:commandLink action="#{archivos.listSetup}" value="Show All Archivos Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/archivos/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Listing Archivos Items</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Listing Archivos Items</h1>
    <h:form styleClass="jsfcrud_list_form">
      <h:outputText escape="false" value="(No Archivos Items Found)<br />" rendered="#{archivos.pagingInfo.itemCount == 0}" />
      <h:panelGroup rendered="#{archivos.pagingInfo.itemCount > 0}">
        <h:outputText value="Item #{archivos.pagingInfo.firstItem + 1}..#{archivos.pagingInfo.lastItem} of #{archivos.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{archivos.prev}" value="Previous #{archivos.pagingInfo.batchSize}" rendered="#{archivos.pagingInfo.firstItem >= archivos.pagingInfo.batchSize}"/>&nbsp;
        <h:commandLink action="#{archivos.next}" value="Next #{archivos.pagingInfo.batchSize}" rendered="#{archivos.pagingInfo.lastItem + archivos.pagingInfo.batchSize <= archivos.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{archivos.next}" value="Remaining #{archivos.pagingInfo.itemCount - archivos.pagingInfo.lastItem}"
                       rendered="#{archivos.pagingInfo.lastItem < archivos.pagingInfo.itemCount && archivos.pagingInfo.lastItem + archivos.pagingInfo.batchSize > archivos.pagingInfo.itemCount}"/>
        <h:dataTable value="#{archivos.archivosItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
          <h:column>
            <f:facet name="header">
              <h:outputText value="Id"/>
            </f:facet>
            <h:outputText value="#{item.id}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Tipo"/>
            </f:facet>
            <h:outputText value="#{item.tipo}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Ruta"/>
            </f:facet>
            <h:outputText value="#{item.ruta}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText escape="false" value="&nbsp;"/>
            </f:facet>
            <h:commandLink value="Show" action="#{archivos.detailSetup}">
              <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][archivos.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Edit" action="#{archivos.editSetup}">
              <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][archivos.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Destroy" action="#{archivos.remove}">
              <f:param name="jsfcrud.currentArchivos" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][archivos.converter].jsfcrud_invoke}"/>
            </h:commandLink>
          </h:column>

        </h:dataTable>
      </h:panelGroup>
      <br />
      <h:commandLink action="#{archivos.createSetup}" value="New Archivos"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />


    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/archivos/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>New Archivos</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>New Archivos</h1>
    <h:form>
      <h:inputHidden id="validateCreateField" validator="#{archivos.validateCreate}" value="value"/>
      <h:panelGrid columns="2">
        <h:outputText value="Tipo:"/>
        <h:inputText id="tipo" value="#{archivos.archivos.tipo}" title="Tipo" required="true" requiredMessage="The tipo field is required." />
        <h:outputText value="Ruta:"/>
        <h:inputText id="ruta" value="#{archivos.archivos.ruta}" title="Ruta" required="true" requiredMessage="The ruta field is required." />
        <h:outputText value="ArchivosadjuntosList:"/>
        <h:selectManyListbox id="archivosadjuntosList" value="#{archivos.archivos.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].archivosadjuntosList}" title="ArchivosadjuntosList" size="6" converter="#{archivosadjuntos.converter}" >
          <f:selectItems value="#{archivosadjuntos.archivosadjuntosItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{archivos.create}" value="Create"/>
      <br />
      <br />
      <h:commandLink action="#{archivos.listSetup}" value="Show All Archivos Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>