marketplaceMTC/marketplaceMTC-war/src/java/com/marketplaceMTC/vista/managedbeans/AdjuntosController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marketplaceMTC.vista.managedbeans;

import com.marketplaceMTC.entities.Adjuntos;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.transaction.UserTransaction;
import com.marketplaceMTC.vista.managedbeans.util.JsfUtil;
import com.marketplaceMTC.vista.managedbeans.util.PagingInfo;
import com.marketplaceMTC.session.AdjuntosFacade;
import java.util.List;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;

/**
 *
 * @author Miguel
 */
public class AdjuntosController {

  public AdjuntosController() {
    pagingInfo = new PagingInfo();
    converter = new AdjuntosConverter();
  }
  private Adjuntos adjuntos = null;
  private List<Adjuntos> adjuntosItems = null;
  private AdjuntosFacade jpaController = null;
  private AdjuntosConverter converter = null;
  private PagingInfo pagingInfo = null;
  @Resource
  private UserTransaction utx = null;
  @PersistenceUnit(unitName = "marketplaceMTC-warPU")
  private EntityManagerFactory emf = null;

  public PagingInfo getPagingInfo() {
    if (pagingInfo.getItemCount() == -1) {
      pagingInfo.setItemCount(getJpaController().count());
    }
    return pagingInfo;
  }

  public AdjuntosFacade getJpaController() {
    if (jpaController == null) {
      FacesContext facesContext = FacesContext.getCurrentInstance();
      jpaController = (AdjuntosFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "adjuntosJpa");
    }
    return jpaController;
  }

  public SelectItem[] getAdjuntosItemsAvailableSelectMany() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), false);
  }

  public SelectItem[] getAdjuntosItemsAvailableSelectOne() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), true);
  }

  public Adjuntos getAdjuntos() {
    if (adjuntos == null) {
      adjuntos = (Adjuntos) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentAdjuntos", converter, null);
    }
    if (adjuntos == null) {
      adjuntos = new Adjuntos();
    }
    return adjuntos;
  }

  public String listSetup() {
    reset(true);
    return "adjuntos_list";
  }

  public String createSetup() {
    reset(false);
    adjuntos = new Adjuntos();
    return "adjuntos_create";
  }

  public String create() {
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().create(adjuntos);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Adjuntos was successfully created.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return listSetup();
  }

  public String detailSetup() {
    return scalarSetup("adjuntos_detail");
  }

  public String editSetup() {
    return scalarSetup("adjuntos_edit");
  }

  private String scalarSetup(String destination) {
    reset(false);
    adjuntos = (Adjuntos) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentAdjuntos", converter, null);
    if (adjuntos == null) {
      String requestAdjuntosString = JsfUtil.getRequestParameter("jsfcrud.currentAdjuntos");
      JsfUtil.addErrorMessage("The adjuntos with id " + requestAdjuntosString + " no longer exists.");
      return relatedOrListOutcome();
    }
    return destination;
  }

  public String edit() {
    String adjuntosString = converter.getAsString(FacesContext.getCurrentInstance(), null, adjuntos);
    String currentAdjuntosString = JsfUtil.getRequestParameter("jsfcrud.currentAdjuntos");
    if (adjuntosString == null || adjuntosString.length() == 0 || !adjuntosString.equals(currentAdjuntosString)) {
      String outcome = editSetup();
      if ("adjuntos_edit".equals(outcome)) {
        JsfUtil.addErrorMessage("Could not edit adjuntos. Try again.");
      }
      return outcome;
    }
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().edit(adjuntos);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Adjuntos was successfully updated.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return detailSetup();
  }

  public String remove() {
    String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentAdjuntos");
    Integer id = new Integer(idAsString);
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().remove(getJpaController().find(id));
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Adjuntos was successfully deleted.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return relatedOrListOutcome();
  }

  private String relatedOrListOutcome() {
    String relatedControllerOutcome = relatedControllerOutcome();
    if (relatedControllerOutcome != null) {
      return relatedControllerOutcome;
    }
    return listSetup();
  }

  public List<Adjuntos> getAdjuntosItems() {
    if (adjuntosItems == null) {
      getPagingInfo();
      adjuntosItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
    }
    return adjuntosItems;
  }

  public String next() {
    reset(false);
    getPagingInfo().nextPage();
    return "adjuntos_list";
  }

  public String prev() {
    reset(false);
    getPagingInfo().previousPage();
    return "adjuntos_list";
  }

  private String relatedControllerOutcome() {
    String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
    String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
    if (relatedControllerString != null && relatedControllerTypeString != null) {
      FacesContext context = FacesContext.getCurrentInstance();
      Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
      try {
        Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
        Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
        return (String) detailSetupMethod.invoke(relatedController);
      } catch (ClassNotFoundException e) {
        throw new FacesException(e);
      } catch (NoSuchMethodException e) {
        throw new FacesException(e);
      } catch (IllegalAccessException e) {
        throw new FacesException(e);
      } catch (InvocationTargetException e) {
        throw new FacesException(e);
      }
    }
    return null;
  }

  private void reset(boolean resetFirstItem) {
    adjuntos = null;
    adjuntosItems = null;
    pagingInfo.setItemCount(-1);
    if (resetFirstItem) {
      pagingInfo.setFirstItem(0);
    }
  }

  public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
    Adjuntos newAdjuntos = new Adjuntos();
    String newAdjuntosString = converter.getAsString(FacesContext.getCurrentInstance(), null, newAdjuntos);
    String adjuntosString = converter.getAsString(FacesContext.getCurrentInstance(), null, adjuntos);
    if (!newAdjuntosString.equals(adjuntosString)) {
      createSetup();
    }
  }

  public Converter getConverter() {
    return converter;
  }
  
}

marketplaceMTC/marketplaceMTC-war/web/servicios/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Editing Servicios</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Editing Servicios</h1>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputText value="Id:"/>
        <h:outputText value="#{servicios.servicios.id}" title="Id" />
        <h:outputText value="Descripcion:"/>
        <h:inputText id="descripcion" value="#{servicios.servicios.descripcion}" title="Descripcion" required="true" requiredMessage="The descripcion field is required." />
        <h:outputText value="Valor:"/>
        <h:inputText id="valor" value="#{servicios.servicios.valor}" title="Valor" required="true" requiredMessage="The valor field is required." />
        <h:outputText value="Estado:"/>
        <h:inputText id="estado" value="#{servicios.servicios.estado}" title="Estado" required="true" requiredMessage="The estado field is required." />
        <h:outputText value="IdCategoria:"/>
        <h:selectOneMenu id="idCategoria" value="#{servicios.servicios.idCategoria}" title="IdCategoria" required="true" requiredMessage="The idCategoria field is required." >
          <f:selectItems value="#{categorias.categoriasItemsAvailableSelectOne}"/>
        </h:selectOneMenu>
        <h:outputText value="IdAdjunto:"/>
        <h:selectOneMenu id="idAdjunto" value="#{servicios.servicios.idAdjunto}" title="IdAdjunto" required="true" requiredMessage="The idAdjunto field is required." >
          <f:selectItems value="#{adjuntos.adjuntosItemsAvailableSelectOne}"/>
        </h:selectOneMenu>
        <h:outputText value="PaquetesdeserviciosList:"/>
        <h:selectManyListbox id="paquetesdeserviciosList" value="#{servicios.servicios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].paquetesdeserviciosList}" title="PaquetesdeserviciosList" size="6" converter="#{paquetesdeservicios.converter}" >
          <f:selectItems value="#{paquetesdeservicios.paquetesdeserviciosItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="TransaccionesList:"/>
        <h:selectManyListbox id="transaccionesList" value="#{servicios.servicios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].transaccionesList}" title="TransaccionesList" size="6" converter="#{transacciones.converter}" >
          <f:selectItems value="#{transacciones.transaccionesItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{servicios.edit}" value="Save">
        <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][servicios.servicios][servicios.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <br />
      <h:commandLink action="#{servicios.detailSetup}" value="Show" immediate="true">
        <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][servicios.servicios][servicios.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <h:commandLink action="#{servicios.listSetup}" value="Show All Servicios Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/servicios/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Listing Servicios Items</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Listing Servicios Items</h1>
    <h:form styleClass="jsfcrud_list_form">
      <h:outputText escape="false" value="(No Servicios Items Found)<br />" rendered="#{servicios.pagingInfo.itemCount == 0}" />
      <h:panelGroup rendered="#{servicios.pagingInfo.itemCount > 0}">
        <h:outputText value="Item #{servicios.pagingInfo.firstItem + 1}..#{servicios.pagingInfo.lastItem} of #{servicios.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{servicios.prev}" value="Previous #{servicios.pagingInfo.batchSize}" rendered="#{servicios.pagingInfo.firstItem >= servicios.pagingInfo.batchSize}"/>&nbsp;
        <h:commandLink action="#{servicios.next}" value="Next #{servicios.pagingInfo.batchSize}" rendered="#{servicios.pagingInfo.lastItem + servicios.pagingInfo.batchSize <= servicios.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{servicios.next}" value="Remaining #{servicios.pagingInfo.itemCount - servicios.pagingInfo.lastItem}"
                       rendered="#{servicios.pagingInfo.lastItem < servicios.pagingInfo.itemCount && servicios.pagingInfo.lastItem + servicios.pagingInfo.batchSize > servicios.pagingInfo.itemCount}"/>
        <h:dataTable value="#{servicios.serviciosItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
          <h:column>
            <f:facet name="header">
              <h:outputText value="Id"/>
            </f:facet>
            <h:outputText value="#{item.id}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Descripcion"/>
            </f:facet>
            <h:outputText value="#{item.descripcion}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Valor"/>
            </f:facet>
            <h:outputText value="#{item.valor}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Estado"/>
            </f:facet>
            <h:outputText value="#{item.estado}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="IdCategoria"/>
            </f:facet>
            <h:outputText value="#{item.idCategoria}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="IdAdjunto"/>
            </f:facet>
            <h:outputText value="#{item.idAdjunto}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText escape="false" value="&nbsp;"/>
            </f:facet>
            <h:commandLink value="Show" action="#{servicios.detailSetup}">
              <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][servicios.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Edit" action="#{servicios.editSetup}">
              <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][servicios.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Destroy" action="#{servicios.remove}">
              <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][servicios.converter].jsfcrud_invoke}"/>
            </h:commandLink>
          </h:column>

        </h:dataTable>
      </h:panelGroup>
      <br />
      <h:commandLink action="#{servicios.createSetup}" value="New Servicios"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />


    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/servicios/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>New Servicios</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>New Servicios</h1>
    <h:form>
      <h:inputHidden id="validateCreateField" validator="#{servicios.validateCreate}" value="value"/>
      <h:panelGrid columns="2">
        <h:outputText value="Descripcion:"/>
        <h:inputText id="descripcion" value="#{servicios.servicios.descripcion}" title="Descripcion" required="true" requiredMessage="The descripcion field is required." />
        <h:outputText value="Valor:"/>
        <h:inputText id="valor" value="#{servicios.servicios.valor}" title="Valor" required="true" requiredMessage="The valor field is required." />
        <h:outputText value="Estado:"/>
        <h:inputText id="estado" value="#{servicios.servicios.estado}" title="Estado" required="true" requiredMessage="The estado field is required." />
        <h:outputText value="IdCategoria:"/>
        <h:selectOneMenu id="idCategoria" value="#{servicios.servicios.idCategoria}" title="IdCategoria" required="true" requiredMessage="The idCategoria field is required." >
          <f:selectItems value="#{categorias.categoriasItemsAvailableSelectOne}"/>
        </h:selectOneMenu>
        <h:outputText value="IdAdjunto:"/>
        <h:selectOneMenu id="idAdjunto" value="#{servicios.servicios.idAdjunto}" title="IdAdjunto" required="true" requiredMessage="The idAdjunto field is required." >
          <f:selectItems value="#{adjuntos.adjuntosItemsAvailableSelectOne}"/>
        </h:selectOneMenu>
        <h:outputText value="PaquetesdeserviciosList:"/>
        <h:selectManyListbox id="paquetesdeserviciosList" value="#{servicios.servicios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].paquetesdeserviciosList}" title="PaquetesdeserviciosList" size="6" converter="#{paquetesdeservicios.converter}" >
          <f:selectItems value="#{paquetesdeservicios.paquetesdeserviciosItemsAvailableSelectMany}"/>
        </h:selectManyListbox>
        <h:outputText value="TransaccionesList:"/>
        <h:selectManyListbox id="transaccionesList" value="#{servicios.servicios.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].transaccionesList}" title="TransaccionesList" size="6" converter="#{transacciones.converter}" >
          <f:selectItems value="#{transacciones.transaccionesItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{servicios.create}" value="Create"/>
      <br />
      <br />
      <h:commandLink action="#{servicios.listSetup}" value="Show All Servicios Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>