marketplaceMTC/marketplaceMTC-war/src/java/com/marketplaceMTC/vista/managedbeans/ServiciosController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marketplaceMTC.vista.managedbeans;

import com.marketplaceMTC.entities.Servicios;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.transaction.UserTransaction;
import com.marketplaceMTC.vista.managedbeans.util.JsfUtil;
import com.marketplaceMTC.vista.managedbeans.util.PagingInfo;
import com.marketplaceMTC.session.ServiciosFacade;
import java.util.List;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;

/**
 *
 * @author Miguel
 */
public class ServiciosController {

  public ServiciosController() {
    pagingInfo = new PagingInfo();
    converter = new ServiciosConverter();
  }
  private Servicios servicios = null;
  private List<Servicios> serviciosItems = null;
  private ServiciosFacade jpaController = null;
  private ServiciosConverter converter = null;
  private PagingInfo pagingInfo = null;
  @Resource
  private UserTransaction utx = null;
  @PersistenceUnit(unitName = "marketplaceMTC-warPU")
  private EntityManagerFactory emf = null;

  public PagingInfo getPagingInfo() {
    if (pagingInfo.getItemCount() == -1) {
      pagingInfo.setItemCount(getJpaController().count());
    }
    return pagingInfo;
  }

  public ServiciosFacade getJpaController() {
    if (jpaController == null) {
      FacesContext facesContext = FacesContext.getCurrentInstance();
      jpaController = (ServiciosFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "serviciosJpa");
    }
    return jpaController;
  }

  public SelectItem[] getServiciosItemsAvailableSelectMany() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), false);
  }

  public SelectItem[] getServiciosItemsAvailableSelectOne() {
    return JsfUtil.getSelectItems(getJpaController().findAll(), true);
  }

  public Servicios getServicios() {
    if (servicios == null) {
      servicios = (Servicios) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentServicios", converter, null);
    }
    if (servicios == null) {
      servicios = new Servicios();
    }
    return servicios;
  }

  public String listSetup() {
    reset(true);
    return "servicios_list";
  }

  public String createSetup() {
    reset(false);
    servicios = new Servicios();
    return "servicios_create";
  }

  public String create() {
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().create(servicios);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Servicios was successfully created.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return listSetup();
  }

  public String detailSetup() {
    return scalarSetup("servicios_detail");
  }

  public String editSetup() {
    return scalarSetup("servicios_edit");
  }

  private String scalarSetup(String destination) {
    reset(false);
    servicios = (Servicios) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentServicios", converter, null);
    if (servicios == null) {
      String requestServiciosString = JsfUtil.getRequestParameter("jsfcrud.currentServicios");
      JsfUtil.addErrorMessage("The servicios with id " + requestServiciosString + " no longer exists.");
      return relatedOrListOutcome();
    }
    return destination;
  }

  public String edit() {
    String serviciosString = converter.getAsString(FacesContext.getCurrentInstance(), null, servicios);
    String currentServiciosString = JsfUtil.getRequestParameter("jsfcrud.currentServicios");
    if (serviciosString == null || serviciosString.length() == 0 || !serviciosString.equals(currentServiciosString)) {
      String outcome = editSetup();
      if ("servicios_edit".equals(outcome)) {
        JsfUtil.addErrorMessage("Could not edit servicios. Try again.");
      }
      return outcome;
    }
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().edit(servicios);
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Servicios was successfully updated.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return detailSetup();
  }

  public String remove() {
    String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentServicios");
    Integer id = new Integer(idAsString);
    try {
      utx.begin();
    } catch (Exception ex) {
    }
    try {
      Exception transactionException = null;
      getJpaController().remove(getJpaController().find(id));
      try {
        utx.commit();
      } catch (javax.transaction.RollbackException ex) {
        transactionException = ex;
      } catch (Exception ex) {
      }
      if (transactionException == null) {
        JsfUtil.addSuccessMessage("Servicios was successfully deleted.");
      } else {
        JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
      }
    } catch (Exception e) {
      try {
        utx.rollback();
      } catch (Exception ex) {
      }
      JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
      return null;
    }
    return relatedOrListOutcome();
  }

  private String relatedOrListOutcome() {
    String relatedControllerOutcome = relatedControllerOutcome();
    if (relatedControllerOutcome != null) {
      return relatedControllerOutcome;
    }
    return listSetup();
  }

  public List<Servicios> getServiciosItems() {
    if (serviciosItems == null) {
      getPagingInfo();
      serviciosItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
    }
    return serviciosItems;
  }

  public String next() {
    reset(false);
    getPagingInfo().nextPage();
    return "servicios_list";
  }

  public String prev() {
    reset(false);
    getPagingInfo().previousPage();
    return "servicios_list";
  }

  private String relatedControllerOutcome() {
    String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
    String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
    if (relatedControllerString != null && relatedControllerTypeString != null) {
      FacesContext context = FacesContext.getCurrentInstance();
      Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
      try {
        Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
        Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
        return (String) detailSetupMethod.invoke(relatedController);
      } catch (ClassNotFoundException e) {
        throw new FacesException(e);
      } catch (NoSuchMethodException e) {
        throw new FacesException(e);
      } catch (IllegalAccessException e) {
        throw new FacesException(e);
      } catch (InvocationTargetException e) {
        throw new FacesException(e);
      }
    }
    return null;
  }

  private void reset(boolean resetFirstItem) {
    servicios = null;
    serviciosItems = null;
    pagingInfo.setItemCount(-1);
    if (resetFirstItem) {
      pagingInfo.setFirstItem(0);
    }
  }

  public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
    Servicios newServicios = new Servicios();
    String newServiciosString = converter.getAsString(FacesContext.getCurrentInstance(), null, newServicios);
    String serviciosString = converter.getAsString(FacesContext.getCurrentInstance(), null, servicios);
    if (!newServiciosString.equals(serviciosString)) {
      createSetup();
    }
  }

  public Converter getConverter() {
    return converter;
  }
  
}

marketplaceMTC/marketplaceMTC-war/web/categorias/Detail.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Categorias Detail</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Categorias Detail</h1>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputText value="Id:"/>
        <h:outputText value="#{categorias.categorias.id}" title="Id" />
        <h:outputText value="Descripcion:"/>
        <h:outputText value="#{categorias.categorias.descripcion}" title="Descripcion" />

        <h:outputText value="ServiciosList:" />
        <h:panelGroup>
          <h:outputText rendered="#{empty categorias.categorias.serviciosList}" value="(No Items)"/>
          <h:dataTable value="#{categorias.categorias.serviciosList}" var="item" 
                       border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px" 
                       rendered="#{not empty categorias.categorias.serviciosList}">
            <h:column>
              <f:facet name="header">
                <h:outputText value="Id"/>
              </f:facet>
              <h:outputText value="#{item.id}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="Descripcion"/>
              </f:facet>
              <h:outputText value="#{item.descripcion}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="Valor"/>
              </f:facet>
              <h:outputText value="#{item.valor}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="Estado"/>
              </f:facet>
              <h:outputText value="#{item.estado}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="IdCategoria"/>
              </f:facet>
              <h:outputText value="#{item.idCategoria}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="IdAdjunto"/>
              </f:facet>
              <h:outputText value="#{item.idAdjunto}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText escape="false" value="&nbsp;"/>
              </f:facet>
              <h:commandLink value="Show" action="#{servicios.detailSetup}">
                <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][categorias.categorias][categorias.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][servicios.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.relatedController" value="categorias" />
                <f:param name="jsfcrud.relatedControllerType" value="com.marketplaceMTC.vista.managedbeans.CategoriasController" />
              </h:commandLink>
              <h:outputText value=" "/>
              <h:commandLink value="Edit" action="#{servicios.editSetup}">
                <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][categorias.categorias][categorias.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][servicios.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.relatedController" value="categorias" />
                <f:param name="jsfcrud.relatedControllerType" value="com.marketplaceMTC.vista.managedbeans.CategoriasController" />
              </h:commandLink>
              <h:outputText value=" "/>
              <h:commandLink value="Destroy" action="#{servicios.destroy}">
                <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][categorias.categorias][categorias.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.currentServicios" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][servicios.converter].jsfcrud_invoke}"/>
                <f:param name="jsfcrud.relatedController" value="categorias" />
                <f:param name="jsfcrud.relatedControllerType" value="com.marketplaceMTC.vista.managedbeans.CategoriasController" />
              </h:commandLink>
            </h:column>
          </h:dataTable>
        </h:panelGroup>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{categorias.remove}" value="Destroy">
        <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][categorias.categorias][categorias.converter].jsfcrud_invoke}" />
      </h:commandLink>
      <br />
      <br />
      <h:commandLink action="#{categorias.editSetup}" value="Edit">
        <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][categorias.categorias][categorias.converter].jsfcrud_invoke}" />
      </h:commandLink>
      <br />
      <h:commandLink action="#{categorias.createSetup}" value="New Categorias" />
      <br />
      <h:commandLink action="#{categorias.listSetup}" value="Show All Categorias Items"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/categorias/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Editing Categorias</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Editing Categorias</h1>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputText value="Id:"/>
        <h:outputText value="#{categorias.categorias.id}" title="Id" />
        <h:outputText value="Descripcion:"/>
        <h:inputText id="descripcion" value="#{categorias.categorias.descripcion}" title="Descripcion" required="true" requiredMessage="The descripcion field is required." />
        <h:outputText value="ServiciosList:"/>
        <h:selectManyListbox id="serviciosList" value="#{categorias.categorias.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].serviciosList}" title="ServiciosList" size="6" converter="#{servicios.converter}" >
          <f:selectItems value="#{servicios.serviciosItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{categorias.edit}" value="Save">
        <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][categorias.categorias][categorias.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <br />
      <h:commandLink action="#{categorias.detailSetup}" value="Show" immediate="true">
        <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][categorias.categorias][categorias.converter].jsfcrud_invoke}"/>
      </h:commandLink>
      <br />
      <h:commandLink action="#{categorias.listSetup}" value="Show All Categorias Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/categorias/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Listing Categorias Items</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>Listing Categorias Items</h1>
    <h:form styleClass="jsfcrud_list_form">
      <h:outputText escape="false" value="(No Categorias Items Found)<br />" rendered="#{categorias.pagingInfo.itemCount == 0}" />
      <h:panelGroup rendered="#{categorias.pagingInfo.itemCount > 0}">
        <h:outputText value="Item #{categorias.pagingInfo.firstItem + 1}..#{categorias.pagingInfo.lastItem} of #{categorias.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{categorias.prev}" value="Previous #{categorias.pagingInfo.batchSize}" rendered="#{categorias.pagingInfo.firstItem >= categorias.pagingInfo.batchSize}"/>&nbsp;
        <h:commandLink action="#{categorias.next}" value="Next #{categorias.pagingInfo.batchSize}" rendered="#{categorias.pagingInfo.lastItem + categorias.pagingInfo.batchSize <= categorias.pagingInfo.itemCount}"/>&nbsp;
        <h:commandLink action="#{categorias.next}" value="Remaining #{categorias.pagingInfo.itemCount - categorias.pagingInfo.lastItem}"
                       rendered="#{categorias.pagingInfo.lastItem < categorias.pagingInfo.itemCount && categorias.pagingInfo.lastItem + categorias.pagingInfo.batchSize > categorias.pagingInfo.itemCount}"/>
        <h:dataTable value="#{categorias.categoriasItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
          <h:column>
            <f:facet name="header">
              <h:outputText value="Id"/>
            </f:facet>
            <h:outputText value="#{item.id}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="Descripcion"/>
            </f:facet>
            <h:outputText value="#{item.descripcion}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText escape="false" value="&nbsp;"/>
            </f:facet>
            <h:commandLink value="Show" action="#{categorias.detailSetup}">
              <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][categorias.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Edit" action="#{categorias.editSetup}">
              <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][categorias.converter].jsfcrud_invoke}"/>
            </h:commandLink>
            <h:outputText value=" "/>
            <h:commandLink value="Destroy" action="#{categorias.remove}">
              <f:param name="jsfcrud.currentCategorias" value="#{jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][categorias.converter].jsfcrud_invoke}"/>
            </h:commandLink>
          </h:column>

        </h:dataTable>
      </h:panelGroup>
      <br />
      <h:commandLink action="#{categorias.createSetup}" value="New Categorias"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />


    </h:form>
    </body>
  </html>
</f:view>

marketplaceMTC/marketplaceMTC-war/web/categorias/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>New Categorias</title>
      <link rel="stylesheet" type="text/css" href="/marketplaceMTC-war/faces/jsfcrud.css" />
    </head>
    <body>
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h1>New Categorias</h1>
    <h:form>
      <h:inputHidden id="validateCreateField" validator="#{categorias.validateCreate}" value="value"/>
      <h:panelGrid columns="2">
        <h:outputText value="Descripcion:"/>
        <h:inputText id="descripcion" value="#{categorias.categorias.descripcion}" title="Descripcion" required="true" requiredMessage="The descripcion field is required." />
        <h:outputText value="ServiciosList:"/>
        <h:selectManyListbox id="serviciosList" value="#{categorias.categorias.jsfcrud_transform[jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['com.marketplaceMTC.vista.managedbeans.util.JsfUtil'].jsfcrud_method.arrayToList].serviciosList}" title="ServiciosList" size="6" converter="#{servicios.converter}" >
          <f:selectItems value="#{servicios.serviciosItemsAvailableSelectMany}"/>
        </h:selectManyListbox>

      </h:panelGrid>
      <br />
      <h:commandLink action="#{categorias.create}" value="Create"/>
      <br />
      <br />
      <h:commandLink action="#{categorias.listSetup}" value="Show All Categorias Items" immediate="true"/>
      <br />
      <br />
      <h:commandLink value="Index" action="welcome" immediate="true" />

    </h:form>
    </body>
  </html>
</f:view>